from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, END, NORMAL,DISABLED
import subprocess

def get_response(input_text):
    command = f'ollama run llama2 "{input_text}"'
    process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
    stdout, stderr = process.communicate()
    response =stdout.decode().strip()
    return response

def send_message(event=None):
    message = user_input.get()
    if message.strip() != '':
        user_input.delete(0, END)
        response = get_response(message)
        output_text.config(state=NORMAL)
        output_text.insert(END, "You: \n" + message + '\n')
        output_text.insert(END, "llama2: \n" + response + '\n\n')
        output_text.config(state=DISABLED)

#GUI Starts Here !!!


# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/mayankpant/Documents/Code/GitHub Projects/Llama2-Assistant/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.title("Llama2 Assistant")
window.geometry("1300x800")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 800,
    width = 1300,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    778.0,
    370.0,
    image=image_image_1
)

output_text = Text(
    window,
    bd=0,
    bg="#A3A3A3",
    fg="#000716",
    highlightthickness=0,
    font=('Helvetica', 20),
    state="disabled"
)
output_text.place(
    x=298.0,
    y=20.0,
    width=960.0,
    height=698.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    738.0,
    759.5,
    image=entry_image_1
)
user_input = Entry(
    window,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=('Helvetica', 14)
)
user_input.bind("<Return>", send_message)
user_input.place(
    x=298.0,
    y=729.0,
    width=880.0,
    height=59.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    137.0,
    405.0,
    image=image_image_2
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=send_message,
    relief="flat",

)
button_1.place(
    x=1203.0,
    y=729.0,
    width=80.0,
    height=61.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    139.0,
    47.0,
    image=image_image_3
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=17.0,
    y=721.0,
    width=241.0,
    height=69.0
)
window.resizable(False, False)
window.mainloop()
